FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

RUN python3 -m pip install pip --upgrade

RUN mkdir -p /app

WORKDIR /app

ADD requirements.txt /app
RUN pip install -r requirements.txt

ADD . /app

EXPOSE 8000

CMD ["/bin/bash", "-c", "python manage.py migrate; python manage.py runserver 0.0.0.0:8000"]