# Generated by Django 4.1.7 on 2023-03-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "cpf",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="cpf"
                    ),
                ),
                ("birth_date", models.DateField()),
            ],
        ),
    ]
